### PR TITLE
SUBUI-5: Added HttpClient for Submarine API

### LINKED ISSUE #5: Add a HTTP Client for Submarine API
Create a subclass of the `HttpClient` to support Submarine's responses/exceptions so that you can go ahead and subclass this one to create specific resource clients.

### PR DESCRIPTION
**Pull request by joshuaedwardcrowe**
Fixes #5.

### CODE REVIEW

File: src/Http/Headers/HttpClientAcceptHeader.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import HttpClientHeader from "./HttpClientHeader";
+import IHttpClientHeader from "./IHttpClientHeader";
+
+export class HttpClientAcceptHeader extends HttpClientHeader implements IHttpClientHeader {
+    constructor(contentTypes: string[]) {
+        super("Accept", contentTypes.join(", "));
```
Comment (InsertBeforeFlight) [inline src/Http/Headers/HttpClientAcceptHeader.ts:6]: Test this and be sure it follows the format for this kind of header.

File: src/Http/HttpClient.ts [hunk 2]
```diff
@@ -1,8 +1,13 @@
 import IHttpClientHeader from "./Headers/IHttpClientHeader";
+import {HttpClientAcceptHeader} from "./Headers/HttpClientAcceptHeader";
 
 export default abstract class HttpClient {
     protected readonly _headers: IHttpClientHeader[] = [];
 
+    protected _setAcceptHeader(...contentTypes: string[]) {
+        const header = new HttpClientAcceptHeader(contentTypes)
```
Comment (InsertBeforeFlight) [inline src/Http/HttpClient.ts:8]: This may be redundant as a method, this logic isn't complicated.

File: src/SubmarineHttp/SubmarineHttpClient.ts [hunk 3]
```diff
@@ -0,0 +1,82 @@
+import HttpClient from "../Http/HttpClient";
```
Comment (InsertBeforeFlight) [inline src/SubmarineHttp/SubmarineHttpClient.ts:1]: Write unit tests for this.

File: src/SubmarineHttp/SubmarineHttpClient.ts [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+
+    public delete(url: string, options?: RequestInit) {
+        return this._performSubmarineHttpRequest<void, void>(HttpClientMethod.DELETE, url, undefined, options);
+    }
+
+    protected _generateUrl(url: string) {
+        return `${this._version}/${url}`;
+    }
+
+    protected async _performSubmarineHttpRequest<TRequest, TResponse>(method: string, url: string, body?: TRequest, options: RequestInit = {}): Promise<TResponse>  {
```
Comment (InsertBeforeFlight) [inline src/SubmarineHttp/SubmarineHttpClient.ts:39]: Any way to clean this signature up?

File: src/SubmarineHttp/SubmarineHttpClient.ts [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+        const fullUrl = this._generateUrl(url);
+        options.body = JSON.stringify(body);
```
Comment (InsertBeforeFlight) [inline src/SubmarineHttp/SubmarineHttpClient.ts:41]: I feel like this is more of an option for the HTTP method our API supports, rather than an expectation.

File: src/Http/Headers/HttpClientAcceptHeader.ts [hunk 6]
```diff
@@ -0,0 +1,8 @@
+import HttpClientHeader from "./HttpClientHeader";
+import IHttpClientHeader from "./IHttpClientHeader";
+
+export class HttpClientAcceptHeader extends HttpClientHeader implements IHttpClientHeader {
```
Comment (InsertBeforeFlight) [inline src/Http/Headers/HttpClientAcceptHeader.ts:4]: This might be redundant on a whole, perhaps just use a constant for the Header name and use `HttpClientHeader`.
